### PR TITLE
CMake support

### PR DESCRIPTION
**Pull request by uis246**
Created CMakeLists.txt
Added build/ to .gitignore

### CODE REVIEW

**Comment by uis246** [comment]
Now it can be loaded as cmake external project and run even on windows

**Comment by uis246** [comment]
How to build standalone:

mkdir build
cd build
cmake .. -DENABLE_TESTS=ON
make

**Comment by uis246** [comment]
Also tests can be added by default

**Comment by cofyc** [comment]
looks like CMake support is a strong need (https://github.com/cofyc/argparse/pull/21, https://github.com/cofyc/argparse/pull/13)
/lgtm
/approve

**Comment by cofyc** [comment]
FYI @dxramax @hxingpax

**Pull request merged**
